
/*
  A special type of prime is generated by the formula 

		p = 2^m * 3^n + 1 
 
  where m and n can be any non-negative integer.

	The first 5 of these primes are 2, 3, 5, 7, 13, and are generated as follows:

	2 = 2^0 * 3^0 + 1
	3 = 2^1 * 3^0 + 1
	5 = 2^2 * 3^0 + 1
	7 = 2^1 * 3^1 + 1
	13 = 2^2 * 3^1 + 1
	..and so on
 *
 */

#include <iostream>
#include <vector>
#include <cmath>
#include <set>

void printVector(std::vector<long long> filledVector)
{
	for(auto& things: filledVector)
		std::cout << things << ",";

	std::cout << filledVector.size() << ",";
}

std::vector<long long> generatePrimes(int n, int m, char print = 'n')
{
	std::vector<long long> primeTable;
	std::set<long long> primeSet;
	for(int i = 0; i < m; i++)
	{
		for(int j = 0; j < m; j++)
		{
			long long p = ((std::pow(j,2) * std::pow(i,3)) + 1);
			primeTable.push_back(p);
			primeSet.insert(p);
		}
	}
	if(print == 'y')
	{
		printVector(primeTable);
	}
	return primeTable;

}

int main()
{
	auto primes = generatePrimes(1,1000);
	generatePrimes(1,5,'y');

	return 0;
}
